version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: rs-app-$NAME
    ports:
      - $APP_PORT:8050
    volumes:
      - ./:/app
